apiVersion: v1















env:
  - name: DB_HOST
    value: "rds-endpoint"
  - name: DB_PORT
    value: "3306"
  - name: DB_USER
    value: "Administrator"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: password