apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaun-sleep-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kaun-sleep-site
  template:
    metadata:
      labels:
        app: kaun-sleep-site
    spec:
      containers:
      - name: kaun-sleep-site
        image: <aws-account-id>.dkr.ecr.<your-region>.amazonaws.com/kaun-sleep-site:latest
        ports:
        - containerPort: 80