apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaun-sleep-pv
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exported/path 
    server: nfs-server.example.com 
